apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: db-schema
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: db
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password" # Asegúrate de cambiar esta contraseña por algo seguro.
            - name: POSTGRES_DB
              value: "exampledb"
          volumeMounts:
            - name: db-schema
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-schema
          configMap:
            name: db-schema